### ISSUE TITLE
Only one record in the DB from the set of Pre-policy and Post-policy instead of two!

### ISSUE THREAD

**Issue by v1shnya** [OpenBMP/obmp-collector#7] opened 2022-09-19 08:57 UTC
Hi Tim,

in the pcap I've sent to your email you could see **two** BMP records (Pre-policy adj-rib-out AND Post-policy adj-rib-out) for the same prefix. Wireshark filer - "bgp.mp_reach_nlri_ipv4_prefix == 1.1.1.12 && bgp.rd == 172.16.0.22:777 && bmp.peer.ip.addr == 10.141.255.1"

In the postgres database there is only **one** record

openbmp=# SELECT *
from v_l3vpn_routes
where routername = 'LAB-WAN-NE40X8A-01' AND peername = '10.141.255.1' AND rd='172.16.0.22:777' AND prefix='1.1.1.12';
     routername     |   peername   |       rd        |  prefix  | prefixlen | origin | origin_as | med | localpref |     nh
  | as_path | aspath_count | communities |   extcommunities    | largecommunities | clusterlist | aggregator | peeraddress  | p
eerasn | isipv4 | ispeeripv4 | ispeervpn |        lastmodified        |    firstaddedtimestamp     | path_id | labels |
     rib_hash_id              |             base_hash_id             |             peer_hash_id             |            router
_hash_id            | iswithdrawn | isprepolicy | isadjribin
--------------------+--------------+-----------------+----------+-----------+--------+-----------+-----+-----------+-----------
--+---------+--------------+-------------+---------------------+------------------+-------------+------------+--------------+--
-------+--------+------------+-----------+----------------------------+----------------------------+---------+--------+--------
------------------------------+--------------------------------------+--------------------------------------+------------------
--------------------+-------------+-------------+------------
 LAB-WAN-NE40X8A-01 | 10.141.255.1 | 172.16.0.22:777 | 1.1.1.12 |        32 | igp    |     65400 |   0 |         0 | 172.16.0.1
1 | {65400} |            1 | {""}        | {rt=1:1,rt=777:777} | {""}             | {""}        |            | 10.141.255.1 |
 65011 | t      | t          | f         | 2022-09-16 10:31:50.151205 | 2022-09-19 06:55:15.745892 |       0 | 48343  | e3b22d8
f-3ed0-a39d-aff8-d47064e32c28 | d796f99f-5142-008d-817f-9a478d471551 | 8ffbea04-2918-0812-505b-3ee1f70c13cc | a5c70f1a-7a98-e7e
d-4abd-00cf6b4f06bb | f           | f           | f
(1 row)

I believe that we shpould have two distinct records for pre- and post-policy in the DB!

**Comment by TimEvens** [comment] 2022-09-19 20:53
The problem is that the NLRI hash doesn't include RIB type (in vs out) and policy (pre vs post). IMO, this was a miss and will be fixed as part of the hashing. The DB and other programs follow the unique hash_id, so they will automatically update to show each record.  

The problem is that this will introduce hash changes for all the types of messages.  In effort to be backwards compatible, the code can be adapted to include the value in the hash only if it's different than the current default, which is Adj-Rib-In Pre-Policy.  This way, anyone using Out and/or Post policy will get new records but the old/original ones will remain the same. 

Regarding local-rib, local-rib is a different based on peer-type. Currently the hash_id for a peer does not take this into account, but I'll update that.  Local-RIB peers will be unique, which will cause the NLRI updates to have a different hash ID.  

There is a recent grow@ietf.org discussion regarding updating 7854 clarifications on what to send and expectations of the receiver (e.g., OpenBMP).  

For now, I'll update the collector to update the NLRI hash_ids to be unique. I'll specifically support the existing hashing, so only Adj-RIB-Out, Post-Policy and Local-RIB will result in new hash IDs. 

This change will take a few more days.

**Comment by v1shnya** [comment] 2022-09-20 14:53
Tim, let me repeat what you said to better settle it with me. So, in case I've configured on router Adj-Rib-In/Out with Pre- and Post- Policy I would get 4 records in the DB, correct?
- Adj-Rib-In Pre-Policy - hash (rib_hash_id) will not change from as it's now;
- Adj-Rib-In Post-Policy - unique hash including RIB type and policy;
- Adj-Rib-Out Pre-Policy - unique hash including RIB type and policy;
- Adj-Rib-Out Post-Policy - unique hash including RIB type and policy;

About Loc-RIB, let me test how it works now. Looks like I'll come back to you for clarifications

**Comment by TimEvens** [comment] 2022-09-23 13:44
@v1shnya , that is correct. You'll get a record for each.  I plan to make the changes to the collector early next week.

**Comment by v1shnya** [comment] 2022-10-05 15:07
Hi Tim, good day! any progress on fixing?!

**Comment by TimEvens** [comment] 2022-10-10 15:12
I will post a new version today.

**Comment by TimEvens** [comment] 2022-10-10 21:40
@v1shnya , can you give ```openbmp/collector:v2.2.3``` a try now? You should now see a record per in/out rib as well as pre/post policy.  

<img width="1573" alt="image" src="https://user-images.githubusercontent.com/7909839/194956241-ac5f7f0e-f1cc-4ef3-881b-c0cc9ff0eb11.png">

**Comment by v1shnya** [comment] 2022-10-11 15:49
Checked the number of advertised, received and filtered prefixes on routers and on the openbmp dashboard, it's similar. So far looks good. Thank you, Tim!

**Comment by TimEvens** [comment] 2022-10-11 22:13
Great, thanks for checking.  Please let me know if you still have an issue with this item. If not, we can go ahead and close out this issue.

**Closed** 2022-12-22 21:21 UTC
